### ISSUE TITLE
[BUG] state name can't be added as a logger variable

### ISSUE THREAD

**Issue by emekBaris** [UniMelbHumanRoboticsLab/CANOpenRobotController#35]
## Description
It's often useful to log the current state name along with the other parameters.

`logHelper.add(currentState->getName(), "state");` doesn't work because it returns pointer to the name of the state. 

Even if the `State::getName` return type is changed to a reference to pointer( `const char *&getName();`) the following compile error occurs:

> CANOpenRobotController/lib/spdlog/helper/LogHelper.h:104:30: error: no matching function for call to ‘to_string(const char*&)’

Not sure what can be a quick and clean fix.

**Comment by vcrocher** [comment]
We would need to store and return the state name as an std::string and not a const char*. Given it is not much used anywhere else this should be possible without breaking anything and quite useful actually.
Otherwise, a very quick fix is to declare an std::string in your state machine and update it in the update method. If you pass the reference to that string then you are good.
